### ISSUE TITLE
trigger_push bug

### ISSUE THREAD

**Issue by sneak-it** [jason-e/rngfix#1]
Hey rio! Seems as though an odd bug was discovered with rngfix:

https://www.youtube.com/watch?v=M6bftPeqjGA

Map is surf_proximity_final on CS:GO, apparently the same issue occurs on the same map in CS:S. As you can see, disabling rngfix takes care of the issue. I'm assuming it has something to do with upwards slope logic overriding the push speed.

**Comment by jason-e** [comment]
I've determined this is caused by an interaction between rngfix and some pushfix implementations. The offending code in pushfix is:
```c
if(vecAbsDir[2] > 0.0 && GetEntityFlags(other) & FL_ONGROUND)
{
	SetEntPropEnt(other, Prop_Data, "m_hGroundEntity", -1);
	origin[2] += 1.0;
}
```
To anyone with a pushfix implementation that has that behavior, I would recommend removing that block both to fix this interaction, and because that behavior appears to actually be detrimental to the operation of pushfix itself. SlidyBat has updated his implementation shared [here](https://forums.alliedmods.net/showpost.php?p=2561673&postcount=17) to account for this.
